// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2QoSAy0AEu-CgOP2ytB9vpCLsvlC0VRc',
    appId: '1:512795377903:web:711a137f2aeb8319c4db1a',
    messagingSenderId: '512795377903',
    projectId: 'devunder50c',
    authDomain: 'devunder50c.firebaseapp.com',
    storageBucket: 'devunder50c.firebasestorage.app',
    measurementId: 'G-YY3M6HMBJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9n3K6GEu_XgnUySvoM9dTT4jU04iMydc',
    appId: '1:512795377903:android:c2de7fbd957871f3c4db1a',
    messagingSenderId: '512795377903',
    projectId: 'devunder50c',
    storageBucket: 'devunder50c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuE3vJdwvPUShms6CcqTYY-S1PX974f5c',
    appId: '1:512795377903:ios:23b599d77f2b094fc4db1a',
    messagingSenderId: '512795377903',
    projectId: 'devunder50c',
    storageBucket: 'devunder50c.firebasestorage.app',
    iosBundleId: 'com.example.pjdscProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuE3vJdwvPUShms6CcqTYY-S1PX974f5c',
    appId: '1:512795377903:ios:23b599d77f2b094fc4db1a',
    messagingSenderId: '512795377903',
    projectId: 'devunder50c',
    storageBucket: 'devunder50c.firebasestorage.app',
    iosBundleId: 'com.example.pjdscProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2QoSAy0AEu-CgOP2ytB9vpCLsvlC0VRc',
    appId: '1:512795377903:web:55932768a6715077c4db1a',
    messagingSenderId: '512795377903',
    projectId: 'devunder50c',
    authDomain: 'devunder50c.firebaseapp.com',
    storageBucket: 'devunder50c.firebasestorage.app',
    measurementId: 'G-0RM5GEFGEY',
  );

}